### ISSUE TITLE
NFC watchdog is kicking

### ISSUE THREAD

**Issue by pulser** [sonyxperiadev/device-sony-sirius#10]
NFC watchdog is kicking in on Z2, and it's not showing in the UI as being available (greyed out switch, in on position).

Logcat at http://paste.omnirom.org/view/f298029b
(No relevant dmesg content that I can see)

AM write failure (32 / Broken pipe) appears to be the underlying cause

Eventually NFC service dies and toggle goes to off state, but able to be tapped, and hitting the toggle gives 

    E/NFC     ( 1855): NFC service dead - attempting to recover

EDIT: Aha, found the issue:

D/NfcAdaptation( 2535): const CNfcParam* CNfcConfig::find(const char*) const found NCI_HAL_MODULE=nfc_nci.pn54x
E/NfcAdaptation( 2535): NfcAdaptation::InitializeHalDeviceContext: fail hw_get_module nfc_nci.pn54x

**Comment by jerpelea** [comment]
You are missing nfc releated cherry-picks
